version: '2'
services:
  mongo:
    image: "mongo:3"
    volumes:
        - /Users/Leon/Documents/docker/graylog/data/mongo:/data/db
  elasticsearch:
    image: "elasticsearch:2"
    volumes:
        - /Users/Leon/Documents/docker/graylog/data/elasticsearch:/usr/share/elasticsearch/data
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog:
    image: graylog2/server:2.1.2-1
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: http://localhost:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "514:514"
      - "515:515"
